CREATE TABLE IF NOT EXISTS audit_retrieval_record (
  retrieval_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '检索记录ID',
  task_id BIGINT NOT NULL COMMENT '任务ID',
  task_no VARCHAR(64) NOT NULL COMMENT '任务编号',
  workflow_code VARCHAR(64) NOT NULL COMMENT '工作流编码',
  source_chunk_id BIGINT DEFAULT NULL COMMENT '待审核内容片段ID',
  query_text TEXT NOT NULL COMMENT '检索query',
  knowledge_scope JSON DEFAULT NULL COMMENT '知识库范围',
  retrieval_config JSON DEFAULT NULL COMMENT '检索配置',
  kb_request_id VARCHAR(128) DEFAULT '' COMMENT '知识库请求ID',
  request_payload JSON DEFAULT NULL COMMENT '请求快照',
  response_summary JSON DEFAULT NULL COMMENT '响应摘要',
  result_count INT DEFAULT 0 COMMENT '召回数量',
  retrieval_status VARCHAR(20) DEFAULT 'PENDING' COMMENT '状态',
  error_code VARCHAR(64) DEFAULT '' COMMENT '错误码',
  error_msg TEXT COMMENT '错误信息',
  duration_ms BIGINT DEFAULT 0 COMMENT '耗时毫秒',
  create_time DATETIME DEFAULT NULL,
  PRIMARY KEY (retrieval_id),
  KEY idx_audit_retrieval_record_task (task_id),
  KEY idx_audit_retrieval_record_chunk (source_chunk_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI审核知识库检索记录';

CREATE TABLE IF NOT EXISTS audit_retrieval_reference (
  reference_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '检索依据ID',
  retrieval_id BIGINT NOT NULL COMMENT '检索记录ID',
  task_id BIGINT NOT NULL COMMENT '任务ID',
  source_chunk_id BIGINT DEFAULT NULL COMMENT '待审核内容片段ID',
  kb_chunk_id VARCHAR(128) DEFAULT '' COMMENT '知识库片段ID',
  kb_document_id VARCHAR(128) DEFAULT '' COMMENT '知识库文档ID',
  resource_id BIGINT DEFAULT NULL COMMENT '业务文件ID',
  resource_type VARCHAR(32) DEFAULT '' COMMENT '资源类型',
  file_name VARCHAR(255) DEFAULT '' COMMENT '来源文件名',
  file_url VARCHAR(1000) DEFAULT '' COMMENT '来源文件URL',
  version_no VARCHAR(64) DEFAULT '' COMMENT '来源版本',
  page_no INT DEFAULT NULL COMMENT '页码',
  section_title VARCHAR(255) DEFAULT '' COMMENT '章节标题',
  section_path VARCHAR(500) DEFAULT '' COMMENT '章节路径',
  rule_code VARCHAR(128) DEFAULT '' COMMENT '规则编号',
  chunk_text_snapshot MEDIUMTEXT COMMENT '检索时片段文本快照',
  score DECIMAL(10,6) DEFAULT NULL COMMENT '相似度分数',
  rank_score DECIMAL(10,6) DEFAULT NULL COMMENT '重排分数',
  effective_date DATE DEFAULT NULL COMMENT '生效日期',
  status VARCHAR(32) DEFAULT '' COMMENT '知识状态',
  create_time DATETIME DEFAULT NULL,
  PRIMARY KEY (reference_id),
  KEY idx_audit_retrieval_reference_task (task_id),
  KEY idx_audit_retrieval_reference_retrieval (retrieval_id),
  KEY idx_audit_retrieval_reference_chunk (source_chunk_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI审核检索依据快照';
